### ISSUE TITLE
Message When Creating Network

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/ark-desktop#168]
![manage-networks](https://user-images.githubusercontent.com/25795454/28205785-cd641520-6883-11e7-9cc5-03a0d0859a80.jpg)

When creating (maybe it should be renamed to add network?), there is no message anywhere of successfully getting data for auto-configure so it would be nice maybe to inform user if successfully obtained network parameters and also informing them to click on save to add it into the list of manage networks?

**Comment by fileninja** [comment]
I'm totally with you. "create" is a bit misunderstanding because you dont create a new one but adding an existing one. The double button "add" and then "save" in my opinion is a bad design choice. 
How about **replacing** the Save button with "add" and automatically do the save process and print that autp-check message?

**Comment by boldninja** [comment]
@fileninja , I agree with you my fellow ninja member, save + create could be "merged" into "add" and if any errors it will tell you what it is, if successful it will tell you it saved saved successfully

**Comment by fix** [comment]
yes, creation from a node should be revamped, maybe with another popup window or put it in another context... too UX confusing
