### ISSUE TITLE
ark client-cannot delete networks you created/ pressing 'x' sign on client brings you to top account

### ISSUE THREAD

**Issue by thricepi** [ArkEcosystem/ark-desktop#169]
1.)The 'x' button on the ark client seems to just bring you to the first listed account you have for that network but it doesn't close/delete anything.  
2.)It is not clear atm that you can delete networks. It seems you can only delete accounts but not networks.

**Comment by sleepdefic1t** [comment]
@thricepi 
I agree this is confusing.
I saw in the source that it basically closes the accounts dashboard page.
Landing you back to the first listed account.

**Comment by boldninja** [comment]
You'll be able to delete networks with the release of new desktop wallet version it was already coded.

**Comment by sleepdefic1t** [comment]
@thricepi 

Is this the X you mean.
I initially thought it deleted the account from the client.

![screen shot 2017-07-17 at 10 23 39 pm](https://user-images.githubusercontent.com/7477456/28297994-d64e0cdc-6b3e-11e7-84e5-055d31dbe52c.png)

**Comment by zillionn** [comment]
I think this "X" should be removed.

**Comment by sleepdefic1t** [comment]
Agree with @zillionn 

Thinking it through.
This is the page when you click the "Home" tab.
So we're closing home?

It feels like home should be the account landing page.

The "add," "import," and "create" could easily be moved to the bottom on the list view,
below "Watch-Only Addresses."

The network & market cards could also easily be removed since they both have their own tabs.

Unless the "home" page is there for ledger or something else,
it really doesn't make sense for it to be there at all.

**Comment by fix** [comment]
agree this UX is misleading. Will remove it.

**Comment by fileninja** [comment]
@fix do you do this? maybe we should use the Github Assignee-Feature so we dont do duplicate work

**Comment by eugeneli** [comment]
I didn't see anyone doing it so I did it :P 
https://github.com/ArkEcosystem/ark-desktop/pull/181
