### ISSUE TITLE
Testnet/Mainnet function

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#25]
Hi,

Does the desktop client have a switch to move from testnet to mainnet, i know mainnet won't go live until 1st Feb 2017 ish.

Reason i ask is i know that functionality exists within Ethereum wallet, but i don't know whether it's useful for ARK as the client doesn't fully sync the block chain (which is great!)

**Comment by Doweig** [comment]
Hmmm good question. I'm not sure what is the best way to go on this, will check how other projects are doing.
The thing is, the testnet is getting a lot of attention now because mainnet is not live yet. After mainnet is live most people won't care about testnet so it shouldn't be TOO easy to switch between those as it could create unexpected surprises for some people, especially beginners

**Comment by jamiec79** [comment]
agreed. won't testnet still be used even when mainnet is launched?  To test new functions or new releases ahead of releasing into mainnet.  So the delegates that were testing might need the option?

It's not critical. just a useful enhancement i guess...

**Comment by fix** [comment]
Last version: you can swicth from on net to the other

**Comment by jamiec79** [comment]
very true, somehow completely forgot about that... thinking about it we had to change the nethash or something save testnet...

close this one

**Comment by jamiec79** [comment]
resolved.
