### ISSUE TITLE
sending Ark to myself doesn't show the transaction

### ISSUE THREAD

**Issue by wilruns** [ArkEcosystem/ark-desktop#259]
i accidentally sent ark from my address back to myself, in the transactions it shows the minus amount but not the plus amount, however the balance is correct.

correct behaviour should be show both the minus and plus amount

**Comment by fix** [comment]
true that, this is some UI issue, should be improved to make it more intuitive.

**Comment by krau612** [comment]
Because sending/receiving from the same address is actually only 1 transaction with 1 transaction id, it will only show up as 1 transaction in the wallet. I've made a pull request that makes it more clear that you sent Ark and received Ark back (minus the transaction fee) with that same transaction.

**Comment by luciorubeens** [comment]
Fixed in #235
