### ISSUE TITLE
Select Ledger addresses

### ISSUE THREAD

**Issue by digitron-lisk** [ArkEcosystem/ark-desktop#269]
I'd like to see the option to add addresses from the Ledger address pool to the wallet

**Comment by peterdouglas** [comment]
Because Ark doesn't use UTXO, your address remains the same throughout the life of your Ark account - so 1 passphrase = 1 address. If you want to import the wallet directly to the wallet, you should be able to do it using the passphrase. However, that's not ideal for security. We could allow the option to add it as a watch only address when the ledger is not plugged in?

**Comment by fix** [comment]
Hi, we try to follow BIP44 best practice about address discovery.
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery

But as @peterdouglas mentionned, this practice does not make much sense since there is no UTXO, and the idea of BIP44 account discovery was to hide a bit of complexity of UTXO.

As for UX part, i am not sure being able to add manually an extra address is useful. Can you give more details about the use case you have in mind?

**Comment by digitron-lisk** [comment]
Hi fix, I didn't realize you get a new address for each incoming transaction, that is sufficient for me. We can close the issue.
