### ISSUE TITLE
Localisation: New Transaction Dialog

### ISSUE THREAD

**Issue by Spikarija** [ArkEcosystem/ark-desktop#276]
A click on new transaction whilst a language other than English is selected results in the dialog containing several items that are not localised, all enumerated below and emphasized in red inside the attached screencap:
- dialog title which contains what I presume are identifiers for missing translation strings
- "Type an address or a name"
- "QR CODE"
- "REMAINING BALANCE"
- "LOAD TX FROM FILE"
![transaction](https://user-images.githubusercontent.com/31689626/30525636-9da66e36-9c0a-11e7-864d-d20b49c6c3f6.jpg)

**Comment by fix** [comment]
mm likely a bug, i can see translations files are complete. Maybe some issues with character encoding.

**Comment by ckhatri** [comment]
So it looks like for the nl, ko, pt-PT the translation for the top is {{'Send'|translate}} {{ul.network.token}} {{'from'|translate}}. So that's only broken for a few languages.

QR Code doesn't have a translation, but QR Scanner does. 

Remaining Balance and Load TX From File also don't have translations I believe! 

So it just looks like the translations don't exist.

**Comment by fix** [comment]
@luciorubeens spotted the issue: https://github.com/ArkEcosystem/ark-desktop/blob/master/client/app/src/accounts/view/sendArk.html#L5

`translate` should be removed from the span

**Comment by luciorubeens** [comment]
Fixed in c664149de27aba6580c0d3ba33e19c9b33171501
