### ISSUE TITLE
Don't Fixate Just on 1 IP At Fresh Install

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/ark-desktop#516]
Right now if you install ARK desktop on first start it tries to get peers list from 1 fixed IP. If that seed is down it won't be able to get peer list and not able to connect to network. Solution is to not relay on just 1 IP at fresh install, but pool / ping a few from seed servers.

**Comment by Nasicus** [comment]
Maybe I don't fully understand it, but I guess you're talking about the `peerseed`:

```
mainnet: { // so far same as testnet
            nethash: '6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988',
            peerseed: 'http://5.39.9.240:4001',
            forcepeer: false,
            token: 'ARK',
            symbol: 'Ѧ',
            version: 0x17,
            slip44: 111,
            explorer: 'https://explorer.ark.io',
            background: 'url(assets/images/images/Ark.jpg)',
            theme: 'default',
            themeDark: false
          },
```` 
However isn't it a little of a "vicious cycle" problem? Because the call `http://5.39.9.240:4001/api/peers` returns the list of peers...?
Or is the solution simply to provider an array of - let's say -  10 hardcodes peerSeeds which will be static in this file?

**Comment by alexbarnsley** [comment]
That's the solution. I was going to replicate the sort of process as I did on the mobile app. If main fails, it tries the array

**Comment by boldninja** [comment]
@Nasicus exactly, but if http://5.39.9.240:4001/api/peers is down you won't even be able to get a list of peers on a fresh install as this is the only IP it gets peers from.

**Comment by Nasicus** [comment]
@boldninja yes then I understood correctly ;) But it's kind of a vicious cylce :D (Well except for hardcoding multiple ips :) )

@alexbarnsley 
Do you wanna fix it or should I do it?

**Comment by alexbarnsley** [comment]
Feel free to give it a go, and let me know if you have any trouble! I won't get chance to work on it until late tomorrow, or early next week I don't think

**Comment by Nasicus** [comment]
Hmm I guess you're talking about this list:
https://github.com/ArkEcosystem/ark-ts/blob/master/src/config/index.ts

However in `arkjs` there's no such list - right?

So my questions now:

- Should I copy the same list into `ark-desktop`?
- Should I copy the same list into  `arkjs` - make a PR there, then use the updated package in `ark-desktop`? (_better_)
- Should I add `ark-ts` as a package in `ark-desktop` (not sure it works, but it probably should since it's compiled into `js`) and then use the peerList from there? This way we would have no code duplication (_best if it works?_)

What do you guys prefer?

**Comment by alexbarnsley** [comment]
My plan was your option 2, copy the list from ark-node (if different to ark-ts) to ark-js and then use that. However, you could do your option 3. It may add a bit of overhead though in terms of size so option 2 may still be best I guess. Test to see if the size of the built applications goes up drastically

**Comment by Nasicus** [comment]
@alexbarnsley 
Right,  it's probably better to do option 2, because then everyone who uses `arkjs` can also use it, and it's not like that `arkjs` is deprecated :)
