### ISSUE TITLE
Version 1.5.1 triggers Windows Defender SmartScreen warning message before installation

### ISSUE THREAD

**Issue by irkan-hadi** [ArkEcosystem/ark-desktop#543]
Desktop windows client ArkClient-Win64-1.5.1.exe triggers the following message: 

> Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

The message was not triggered by version 1.5.0

Is the publisher info missing?

Using Windows 10 Home N x64

**Comment by Shipwreck** [comment]
Getting this too. SHA256 matches and Malwarebytes / Defender not tripping. I'm gonna just go for it I guess.

**Comment by luciorubeens** [comment]
Hey guys, this version was flagged by the anti virus probably due to electron update, but has already been confirmed as [false positive](https://www.reddit.com/r/ArkEcosystem/comments/7t3qzq/is_this_a_hack_or_a_bug/). We already signed the file for Mac, now we are working on the certification for Windows.
