### ISSUE TITLE
Send ARKs using delegate username

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-desktop#73]
How about when sending ARKs use delegate username not the wallet hex address? I guess you'll only need to use the API to check if that delegate exists and get it's hex address. It'll be a lot easier this way and a lot more people will register delegate/spent 25 ARKs :).

**Comment by fix** [comment]
well even best to use the label that the user can set

**Comment by zillionn** [comment]
The label is not unique, I even set same label for 2 local accounts.

**Comment by dafty-1** [comment]
How to trust the address returned by the API is legit? For example, I could change my node / explorer to always return my address instead of the true one.

Would an address book be better? User saves an alias and an address, and can then select that alias from a dropdown list. Address book is saved in a map on disk, so no third parties to rely on for valid data.

**Comment by dafty-1** [comment]
Duplicated by #107

**Comment by fix** [comment]
yes i agree address book is better, so the user won't be subject to phishing

**Comment by fileninja** [comment]
implemented in #141
